# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Internal Version Check

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:

jobs:
  check-incremented-version:
    name: Check Internal
    run: |
      NEW_VERSION="$(< charm_internal_version)"
      mkdir repo; cd repo
      git clone https://github.com/canonical/mongodb-operator.git
      cd mongodb-operator
      OLD_VERSION="$(< charm_internal_version)"
      [$NEW_VERSION -eq $EXPECTED_NEW_VERSION]

      if [ "$NEW_VERSION" -ne $((OLD_VERSION + 1)) ]; then
        echo "Failure: must increment the internal version"
        # Sending failure signal (non-zero exit code)
        exit 1
      else
        exit 0
      fi
