name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - lib-check
      - ci-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/upload-charm@2.1.0-rc
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.0.0-rc
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "dpe/edge"
