name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets:
      CHARMHUB_TOKEN: "${{ secrets.CHARMHUB_TOKEN }}"
      AWS_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_KEY }}"
      GCP_ACCESS_KEY: "${{ secrets.GCP_ACCESS_KEY }}"
      GCP_SECRET_KEY: "${{ secrets.GCP_SECRET_KEY }}"

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - ci-tests
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # current lib publish is incompatible with bumped APIs - perform this manually. After merge +
      # publish. It should be possible to comment this back in and for the workflow to resume
      # normally.
      # see issue: https://github.com/canonical/charming-actions/issues/97
      # - name: Release any bumped charm libs
      #   uses: canonical/charming-actions/release-libraries@2.4.0
      #   with:
      #     credentials: "${{ secrets.CHARMHUB_TOKEN }}"
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.2.2
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "6/edge"
