name: Release to 6/edge

on:
  push:
    branches:
      - 6/edge

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    permissions:
      contents: write  # Needed for Allure Report beta

  release:
    name: Release charm
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@v29.0.0
    with:
      channel: 6/edge
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create git tags

  release-libraries:
    name: Release libraries
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          # Workaround for https://github.com/canonical/charmcraft/issues/1389#issuecomment-1880921728
          touch requirements.txt
      - name: Release any bumped charm libs
        uses: canonical/charming-actions/release-libraries@2.4.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
